# Generated by Django 2.0.13 on 2019-04-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingIdeas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingideaspost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
